title: Bruno Moreira | CyberSec Portfolio
description: CTF Writeups, Cybersecurity Research & Automotive Security
baseurl: ""
url: "https://draftzz.github.io"
theme: minima
author:
   Bruno Antonio Moreira
   brunomoreira2712@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

permalink: /writeups/:title/
